Repository LikeKNU/LikeKNU-Server, pull requests merged in 2023-10, with the labels that each got.

#37 Fix: 시내버스 상세 조회 커스텀 Comparator 사용
  src/main/java/ac/knu/likeknu/domain/CityBus.java
  src/main/java/ac/knu/likeknu/service/CityBusService.java
Labels: 🐛Bug, 🛠️BackEnd

#35 menu 상세 조회 api
  src/main/java/ac/knu/likeknu/controller/MainController.java
  src/main/java/ac/knu/likeknu/controller/MenuController.java
  src/main/java/ac/knu/likeknu/controller/dto/main/MainMenuResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MealListDto.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MenuListDto.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MenuResponse.java
  src/main/java/ac/knu/likeknu/domain/AcademicCalendar.java
  src/main/java/ac/knu/likeknu/domain/Cafeteria.java
  src/main/java/ac/knu/likeknu/domain/value/CafeteriaName.java
  src/main/java/ac/knu/likeknu/domain/value/MealType.java
  src/main/java/ac/knu/likeknu/service/MainService.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
Labels: 💫Feature, 🛠️BackEnd

#43 Fix: 식단 정렬 코드 수정
  src/main/java/ac/knu/likeknu/controller/MainController.java
  src/main/java/ac/knu/likeknu/controller/MenuController.java
  src/main/java/ac/knu/likeknu/controller/dto/main/MainMenuResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MenuResponse.java
  src/main/java/ac/knu/likeknu/domain/value/CafeteriaName.java
  src/main/java/ac/knu/likeknu/service/MainService.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
  src/test/java/ac/knu/likeknu/controller/MainControllerTest.java
Labels: 🛠️BackEnd

#40 시내버스 상세 조회 기능 테스트
  src/main/java/ac/knu/likeknu/controller/BusController.java
  src/main/java/ac/knu/likeknu/controller/dto/main/MainCityBusResponse.java
  src/main/java/ac/knu/likeknu/domain/value/Campus.java
  src/main/java/ac/knu/likeknu/service/CityBusService.java
  src/test/java/ac/knu/likeknu/controller/BusControllerTest.java
  src/test/java/ac/knu/likeknu/controller/MainControllerTest.java
  src/test/java/ac/knu/likeknu/service/CityBusServiceTest.java
Labels: ✅Test, 🛠️BackEnd

#46 버스 경로 조회 API 속성 수정
  src/main/java/ac/knu/likeknu/controller/dto/citybus/RouteListResponse.java
  src/test/java/ac/knu/likeknu/controller/BusControllerTest.java
  src/test/java/ac/knu/likeknu/service/CityBusServiceTest.java
Labels: 🛠️BackEnd, 🎨Style

#47 셔틀버스 조회 기능
  src/main/java/ac/knu/likeknu/common/EntityGraphNames.java
  src/main/java/ac/knu/likeknu/controller/BusController.java
  src/main/java/ac/knu/likeknu/controller/dto/citybus/RouteListResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/shuttlebus/ShuttleBusesArrivalTimeResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/shuttlebus/ShuttleListResponse.java
  src/main/java/ac/knu/likeknu/domain/CityBus.java
  src/main/java/ac/knu/likeknu/domain/ShuttleBus.java
  src/main/java/ac/knu/likeknu/domain/ShuttleTime.java
  src/main/java/ac/knu/likeknu/domain/value/ShuttleType.java
  src/main/java/ac/knu/likeknu/repository/CityBusRepository.java
  src/main/java/ac/knu/likeknu/repository/ShuttleBusRepository.java
  src/main/java/ac/knu/likeknu/repository/ShuttleRepository.java
  src/main/java/ac/knu/likeknu/service/CityBusService.java
  src/main/java/ac/knu/likeknu/service/ShuttleBusService.java
  src/test/java/ac/knu/likeknu/controller/BusControllerTest.java
Labels: 💫Feature, 🛠️BackEnd

#45 menu api 테스트
  src/main/java/ac/knu/likeknu/controller/MainController.java
  src/main/java/ac/knu/likeknu/domain/Menu.java
  src/main/java/ac/knu/likeknu/service/MainService.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
  src/test/java/ac/knu/likeknu/controller/MainControllerTest.java
  src/test/java/ac/knu/likeknu/controller/MenuControllerTest.java
  src/test/java/ac/knu/likeknu/service/MenuServiceTest.java
Labels: ✅Test, 🛠️BackEnd

#50 Feat: 공지사항 태그 포함
  src/main/java/ac/knu/likeknu/controller/dto/announcement/AnnouncementListResponse.java
  src/test/java/ac/knu/likeknu/controller/AnnouncementControllerTest.java
  src/test/java/ac/knu/likeknu/service/AnnouncementServiceTest.java
  src/test/java/ac/knu/likeknu/utils/TestInstanceFactory.java
Labels: 💫Feature, 🛠️BackEnd

#52 데이터가 없을 경우 빈 리스트를 저장하도록 수정
  src/main/java/ac/knu/likeknu/controller/dto/main/MainMenuResponse.java
Labels: 🛠️BackEnd, 🪓Hotfix

#57 Fix: 공지사항 페이지 당 요소 개수 변경
  src/main/java/ac/knu/likeknu/service/AnnouncementService.java
Labels: 🛠️BackEnd, 🎨Style

#56 트랜잭션 적용
  src/main/java/ac/knu/likeknu/common/LocalTimeComparator.java
  src/main/java/ac/knu/likeknu/domain/CityBus.java
  src/main/java/ac/knu/likeknu/service/AnnouncementService.java
  src/main/java/ac/knu/likeknu/service/CityBusService.java
  src/main/java/ac/knu/likeknu/service/MainService.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
  src/main/java/ac/knu/likeknu/service/ShuttleBusService.java
  src/test/java/ac/knu/likeknu/controller/BusControllerTest.java
Labels: ♻️Refactor, 🛠️BackEnd

#58 Spring Actuator 설정
  build.gradle
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: 💫Feature, 🛠️BackEnd

#51 학사일정 api 구현
  src/main/java/ac/knu/likeknu/controller/ScheduleController.java
  src/main/java/ac/knu/likeknu/controller/dto/main/MainScheduleResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/schedule/ScheduleListDto.java
  src/main/java/ac/knu/likeknu/controller/dto/schedule/ScheduleResponse.java
  src/main/java/ac/knu/likeknu/repository/AcademicCalendarRepository.java
  src/main/java/ac/knu/likeknu/service/ScheduleService.java
Labels: 💫Feature, 🛠️BackEnd
