Repository LikeKNU/LikeKNU-Server, pull requests merged in 2023-11, with the labels that each got.

#65 Refactor: menuService 메소드로 나눠 indent 2 이하로 변경
  src/main/java/ac/knu/likeknu/controller/MenuController.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
Labels: ♻️Refactor, 🛠️BackEnd

#67 Refactor: MainSchedule 최상위 3개, 4주로 변경, 일정이 없으면 빈 리스트로 반환
  src/main/java/ac/knu/likeknu/controller/MainController.java
  src/main/java/ac/knu/likeknu/repository/AcademicCalendarRepository.java
  src/main/java/ac/knu/likeknu/service/MainService.java
Labels: ♻️Refactor, 🛠️BackEnd

#66 신규 기기 등록 기능
  src/main/java/ac/knu/likeknu/controller/DeviceController.java
  src/main/java/ac/knu/likeknu/controller/dto/device/request/DeviceRegistrationRequest.java
  src/main/java/ac/knu/likeknu/domain/Device.java
  src/main/java/ac/knu/likeknu/service/DeviceService.java
Labels: 💫Feature, 🛠️BackEnd

#69 기기 구독 정보 조회 및 수정
  src/main/java/ac/knu/likeknu/controller/DevicesController.java
  src/main/java/ac/knu/likeknu/controller/dto/device/SubscribeTagListResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/device/SubscribeTagsUpdateRequest.java
  src/main/java/ac/knu/likeknu/controller/dto/device/TagName.java
  src/main/java/ac/knu/likeknu/domain/Device.java
  src/main/java/ac/knu/likeknu/domain/value/Tag.java
  src/main/java/ac/knu/likeknu/repository/DevicesRepository.java
  src/main/java/ac/knu/likeknu/service/DevicesService.java
Labels: 💫Feature, 🛠️BackEnd

#72 시내버스 조회 API 대규모 변경
  src/main/java/ac/knu/likeknu/controller/BusController.java
  src/main/java/ac/knu/likeknu/controller/dto/citybus/CityBusesArrivalTimeResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/citybus/CityBusesResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/citybus/RouteListResponse.java
  src/main/java/ac/knu/likeknu/controller/dto/main/MainCityBusResponse.java
  src/main/java/ac/knu/likeknu/domain/value/RouteType.java
  src/main/java/ac/knu/likeknu/exception/ErrorMessage.java
  src/main/java/ac/knu/likeknu/repository/RouteRepository.java
  src/main/java/ac/knu/likeknu/service/CityBusService.java
  src/main/resources/templates/test.json
  src/test/java/ac/knu/likeknu/controller/BusControllerTest.java
  src/test/java/ac/knu/likeknu/service/CityBusServiceTest.java
Labels: 💫Feature, 🛠️BackEnd

#74 등교버스, 순환버스 통합
  src/main/java/ac/knu/likeknu/controller/BusController.java
  src/main/java/ac/knu/likeknu/repository/ShuttleRepository.java
  src/main/java/ac/knu/likeknu/service/ShuttleBusService.java
Labels: 💫Feature, 🛠️BackEnd

#75 기기 푸시알림 켜기/끄기 기능
  src/main/java/ac/knu/likeknu/controller/DeviceController.java
  src/main/java/ac/knu/likeknu/controller/DevicesController.java
  src/main/java/ac/knu/likeknu/controller/dto/device/request/ChangeNotificationRequest.java
  src/main/java/ac/knu/likeknu/controller/dto/device/response/TurnOnNotificationResponse.java
  src/main/java/ac/knu/likeknu/domain/Device.java
  src/main/java/ac/knu/likeknu/repository/DevicesRepository.java
  src/main/java/ac/knu/likeknu/service/DeviceService.java
  src/main/java/ac/knu/likeknu/service/DevicesService.java
Labels: 💫Feature, 🛠️BackEnd

#77 hotfix: 학사일정 요일 locale 한국 설정
  .gitignore
  scripts/stop.sh
  src/main/java/ac/knu/likeknu/controller/dto/schedule/ScheduleListDto.java
  src/main/resources/application-prod.properties
Labels: 🛠️BackEnd, 🪓Hotfix

#78 Feat: 메인 화면 식단에 mealType 추가
  src/main/java/ac/knu/likeknu/controller/dto/main/MainMenuResponse.java
  src/main/java/ac/knu/likeknu/domain/value/MealType.java
  src/test/java/ac/knu/likeknu/controller/MainControllerTest.java
Labels: 💫Feature, 🛠️BackEnd

#79 Feat: 23시 59분까지 저녁을, 자정 이후로 아침을 보여주도록 수정
  .gitignore
  src/main/java/ac/knu/likeknu/domain/value/MealType.java
  src/main/java/ac/knu/likeknu/service/MainService.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
Labels: 💫Feature, 🛠️BackEnd

#81 fix: 신관 식당 이름 변경
  src/main/java/ac/knu/likeknu/domain/value/CafeteriaName.java
  src/main/resources/application.properties
Labels: 💫Feature, 🛠️BackEnd

#80 Feat: 날짜에 따라 메뉴를 출력하는 기능 구현
  src/main/java/ac/knu/likeknu/controller/MenuController.java
  src/main/java/ac/knu/likeknu/controller/dto/base/MenuResponseData.java
  src/main/java/ac/knu/likeknu/controller/dto/base/MenuResponseDto.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
  src/test/java/ac/knu/likeknu/controller/MenuControllerTest.java
  src/test/java/ac/knu/likeknu/service/MenuServiceTest.java
Labels: 💫Feature, 🛠️BackEnd

#82 사용자 기기 플랫폼 수집 및 마지막 접속 시간 추적
  src/main/java/ac/knu/likeknu/controller/dto/device/request/DeviceRegistrationRequest.java
  src/main/java/ac/knu/likeknu/domain/Device.java
  src/main/java/ac/knu/likeknu/service/DeviceService.java
Labels: 💫Feature, 🛠️BackEnd

#84 feat: 이틀치 menu를 보내는 코드
  src/main/java/ac/knu/likeknu/controller/MenuController.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MealListDto.java
  src/main/java/ac/knu/likeknu/controller/dto/menu/MenuResponse.java
  src/main/java/ac/knu/likeknu/service/MenuService.java
  src/test/java/ac/knu/likeknu/controller/MenuControllerTest.java
  src/test/java/ac/knu/likeknu/service/MenuServiceTest.java
Labels: 💫Feature, 🛠️BackEnd
